# fly.toml app configuration file generated for plant-dashboard on 2025-06-20T10:58:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plant-dashboard'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # ← 自動停止をやめる
  auto_start_machines = true
  min_machines_running = 1    # ← 常に1台稼働させる
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data_volume"
  destination = "/app/db"


